Creating Numpy Array

In [1]:
import numpy  as np

In [2]:
np.array([3,5,89,43]) # 1D Array (also called as Vector)

array([ 3,  5, 89, 43])

In [3]:
a=np.array([3,5,89,43])
print(a)

[ 3  5 89 43]


In [4]:
type(a)

numpy.ndarray

In [5]:
np.array([[3,89,65,48,87],[23,98,91,83,65]]) # 2D Array (is also caled as matrix)

array([[ 3, 89, 65, 48, 87],
       [23, 98, 91, 83, 65]])

In [6]:
np.array([[23,98,76,47],[82,49,20,30],[6,8,23,12]]) #3D Array (is also called Tensor)

array([[23, 98, 76, 47],
       [82, 49, 20, 30],
       [ 6,  8, 23, 12]])

dtype

In [7]:
np.array([34,5,6],dtype=float)

array([34.,  5.,  6.])

In [8]:
np.array([34,5,6],dtype=bool)

array([ True,  True,  True])

In [9]:
np.array([34,5,6],dtype=complex)

array([34.+0.j,  5.+0.j,  6.+0.j])

In [10]:
np.array([34,5,6],dtype=str)

array(['34', '5', '6'], dtype='<U2')

arange

In [11]:
np.arange(3)

array([0, 1, 2])

In [12]:
np.arange(2,6)

array([2, 3, 4, 5])

In [13]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

reshape


In [14]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [15]:
np.arange(1,11).reshape(5,2 ,order='F')

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [16]:
np.arange(1,11).reshape(2,5 ,order='A')

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [17]:
np.arange(1,15).reshape(2,7,order='A')

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [18]:
np.arange(1,9).reshape(2,4,order='A')

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
np.arange(1,9).reshape(1,8,order='A')

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [20]:
np.arange(1,9).reshape(4,2,order='A')

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

ones and zeros

In [21]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [23]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
np.zeros((3,4),dtype=bool)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [25]:
np.zeros((3,4),dtype=complex)

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])

In [26]:
np.random.random((3,8))

array([[0.37316299, 0.72341503, 0.9863882 , 0.85208209, 0.10671507,
        0.63321301, 0.4615447 , 0.92055479],
       [0.77017308, 0.39080094, 0.07076801, 0.18681068, 0.85134342,
        0.3870425 , 0.20121116, 0.00476523],
       [0.97570685, 0.74867334, 0.54410896, 0.10243703, 0.16342454,
        0.75907584, 0.68296828, 0.86401632]])

In [27]:
np.random.rand(3,8)

array([[0.81472781, 0.07326879, 0.86303726, 0.81973562, 0.35810608,
        0.09878222, 0.21997543, 0.87604595],
       [0.0109844 , 0.3232657 , 0.68739999, 0.45563896, 0.79167555,
        0.48094766, 0.36110208, 0.00147575],
       [0.02107619, 0.19313245, 0.40499583, 0.34942856, 0.90572784,
        0.71427624, 0.5651796 , 0.81609902]])

linespace

In [28]:
np.linspace(-2,50,10)

array([-2.        ,  3.77777778,  9.55555556, 15.33333333, 21.11111111,
       26.88888889, 32.66666667, 38.44444444, 44.22222222, 50.        ])

In [29]:
np.linspace(2,20,100)

array([ 2.        ,  2.18181818,  2.36363636,  2.54545455,  2.72727273,
        2.90909091,  3.09090909,  3.27272727,  3.45454545,  3.63636364,
        3.81818182,  4.        ,  4.18181818,  4.36363636,  4.54545455,
        4.72727273,  4.90909091,  5.09090909,  5.27272727,  5.45454545,
        5.63636364,  5.81818182,  6.        ,  6.18181818,  6.36363636,
        6.54545455,  6.72727273,  6.90909091,  7.09090909,  7.27272727,
        7.45454545,  7.63636364,  7.81818182,  8.        ,  8.18181818,
        8.36363636,  8.54545455,  8.72727273,  8.90909091,  9.09090909,
        9.27272727,  9.45454545,  9.63636364,  9.81818182, 10.        ,
       10.18181818, 10.36363636, 10.54545455, 10.72727273, 10.90909091,
       11.09090909, 11.27272727, 11.45454545, 11.63636364, 11.81818182,
       12.        , 12.18181818, 12.36363636, 12.54545455, 12.72727273,
       12.90909091, 13.09090909, 13.27272727, 13.45454545, 13.63636364,
       13.81818182, 14.        , 14.18181818, 14.36363636, 14.54

identity 

In [30]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [32]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

Array Attributes

In [33]:
a1=np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
a2=np.arange(12, dtype=float).reshape(3,4)
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [35]:
a3=np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

ndim

In [36]:
a1.ndim

1

In [37]:
a2.ndim

2

In [38]:
a3.ndim

3

shape

In [39]:
a1.shape

(10,)

In [40]:
a2.shape

(3, 4)

In [41]:
a3.shape

(2, 2, 2)

size

In [42]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [43]:
a3.size

8

In [44]:
a2.size

12

In [45]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
a1.size

10

item size

In [47]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
a1.itemsize # bytes

4

In [49]:
a2.itemsize # integer 64 gives = 8 bytes

8

In [50]:
a3.itemsize   # integer 32 gives = 4 bytes

4

dtype

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

 Changing Data Type


In [51]:
#astype
x = np.array([33, 22, 2.5])
x

array([33. , 22. ,  2.5])

In [52]:
x = np.array([33, 22, 2.5] ,dtype=int)
x

array([33, 22,  2])

In [53]:
x.astype(int)
x

array([33, 22,  2])

 Array operations


In [54]:
z1=np.arange(12).reshape(3,4)
z2=np.arange(12,24).reshape(3,4)

In [55]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [56]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Scalar Operation

In [57]:
#Arithmetic
z1+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [58]:
#Subsraction
z1-2

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [59]:
#Multipication
z1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [60]:
#Power
z1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [61]:
#Modulo
z1%2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]], dtype=int32)

Relational Operators

In [62]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [63]:
z2>2

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [64]:
z2<2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [65]:
z2>15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

 Vector Operation

In [66]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [67]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [68]:
#Arithmetic
z1+z2 # both numpy array Shape is same , we can add item wise

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [69]:
#Substraction
z1-z2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [70]:
#Multiplication
z1*z2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [71]:
#division
z1/z2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

 Array Functions

In [72]:
k1=np.random.random((3,3))
k1

array([[0.67206327, 0.48201158, 0.82628855],
       [0.28259046, 0.59952928, 0.13541228],
       [0.49859815, 0.66892221, 0.18923959]])

In [73]:
k1=np.random.random((3,3))
k1=np.round(k1*100)
k1

array([[11., 27., 91.],
       [64., 31., 49.],
       [13.,  5., 38.]])

In [74]:
#Max
np.max(k1)

91.0

In [75]:
#Min
np.min(k1)

5.0

In [76]:
#Sum
np.sum(k1)

329.0

In [77]:
#prod------->Multipication
np.prod(k1)

6489818375040.0

In [78]:
k1
# 0 = column , 1 = row------>Nnmpy


array([[11., 27., 91.],
       [64., 31., 49.],
       [13.,  5., 38.]])

In [79]:
 # if we want maximum of every row
np.max(k1,axis=1)

array([91., 64., 38.])

In [80]:
 # maximum of every column
 np.max(k1, axis = 0)

array([64., 31., 91.])

In [81]:
# product of every column
np.prod(k1, axis = 0)

array([  9152.,   4185., 169442.])

 Statistics related fuctions


In [82]:
#mean
k1

array([[11., 27., 91.],
       [64., 31., 49.],
       [13.,  5., 38.]])

In [83]:
np.mean(k1)

36.55555555555556

In [84]:
 # mean of every column
k1.mean(axis=0)

array([29.33333333, 21.        , 59.33333333])

In [85]:
# median
np.median(k1)

31.0

In [86]:
np.median(k1, axis = 1)

array([27., 49., 13.])

In [87]:
 # Standard deviation
np.std(k1)

26.24716327999873

In [88]:
np.std(k1, axis = 1)

array([34.56395039, 13.49073756, 14.05544576])

In [89]:
# variance
np.var(k1)

688.9135802469136

In [90]:
np.var(k1, axis = 1)

array([1194.66666667,  182.        ,  197.55555556])

 Trignometry Functions


In [91]:
 np.sin(k1) # sin 

array([[-0.99999021,  0.95637593,  0.10598751],
       [ 0.92002604, -0.40403765, -0.95375265],
       [ 0.42016704, -0.95892427,  0.29636858]])

In [92]:
 np.cos(k1)


array([[ 0.0044257 , -0.29213881, -0.99436746],
       [ 0.39185723,  0.91474236,  0.30059254],
       [ 0.90744678,  0.28366219,  0.95507364]])

In [93]:
 np.tan(k1)


array([[-2.25950846e+02, -3.27370380e+00, -1.06587872e-01],
       [ 2.34786031e+00, -4.41695568e-01, -3.17290855e+00],
       [ 4.63021133e-01, -3.38051501e+00,  3.10309661e-01]])

 dot product


In [94]:
 s2 = np.arange(12).reshape(3,4)
 s3 = np.arange(12,24).reshape(4,3)

In [95]:
s2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [96]:
s3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [97]:
np.dot(s2,s3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

 Log and Exponents

In [98]:
np.exp(s2)


array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

round / floor /ceil


In [99]:
# Round to the nearest integer
arr = np.array([1.2, 2.7, 3.5, 4.9])
rounded_arr = np.round(arr)
print(rounded_arr) 

[1. 3. 4. 5.]


In [100]:
# Round to two decimals
arr = np.array([1.234, 2.567, 3.891])
rounded_arr = np.round(arr, decimals=2)
print(rounded_arr) 

[1.23 2.57 3.89]


In [101]:
# Floor operation
arr = np.array([1.2, 2.7, 3.5, 4.9])
floored_arr = np.floor(arr)
print(floored_arr)

[1. 2. 3. 4.]


In [102]:
np.random.random((2,3))

array([[0.48067866, 0.75407118, 0.06195147],
       [0.12531077, 0.33866871, 0.45274937]])

In [103]:
np.floor(np.random.random((2,3))*100) # gives the smallest integer ex :6.8 =6

array([[34., 70., 21.],
       [63., 41., 78.]])

In [104]:
arr = np.array([1.2, 2.7, 3.5, 4.9])
ceiled_arr = np.ceil(arr)
print(ceiled_arr)

[2. 3. 4. 5.]


In [105]:
 np.ceil(np.random.random((2,3))*100) # gives highest integer ex : 7.8 = 8


array([[41., 64., 11.],
       [32., 25., 90.]])

Indexing and slicing
